# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7380696d09eda227557c1423f8f592cee3576b8615f72cbd87d1d6514c6f94c2fcfe659ee433efb40f61faf0db106d5eb5dda11316476bac0448c055aabb1a36

test:
  secret_key_base: 900d7eaa27ddbbb6da38b9edef63ae8a066dffb4921ed5b8c379330d7a5681a3bdb4c04320334cbb716b1b2bc713e5f61a889c3bd75adc86247d068d726d7661

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
